name: gradio
version: '6.0'
summary: A GTK3 app for finding and listening to internet radio stations 
description: |
  Search and find radio stations, listen to them, and this 
  without needing to use a browser or enter an internet radio stream URL.
  
  Gradio uses the community-based ‘Radio Browser‘ website for its database 
  backend. 
icon: de.haeckerfelix.gradio.svg

grade: devel
confinement: strict

plugs:
  gnome-3-24-platform:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform

apps:
  gradio:
    command: |
      desktop-launch pulse-launch $SNAP/usr/bin/gradio
    plugs:
      - network
      - pulseaudio
      - unity7
      - gsettings
      - x11
      - home
      - gnome-3-24-platform

slots:
  gradio:
    interface: dbus
    bus: session
    name: de.haeckerfelix.gradio
  gradio-mpris:
    interface: mpris
    name: gradio

parts:
  prepare:
    plugin: nil
    prepare: |
      echo "deb http://ppa.launchpad.net/ubuntu-desktop/gnome-3-24/ubuntu xenial main" | tee /etc/apt/sources.list.d/gnome-3-24.list
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 399B698EEA9EF163B6F9A0F62CC98497A1231595
      apt update
      apt upgrade -yy

  files:
    plugin: dump
    source: snap-files
    prepare: |
      chmod +x pulse-launch
    organize:
      pulse-launch: bin/pulse-launch

  gradio:
    after: [desktop-gnome-platform, prepare]
    plugin: meson
    source: https://github.com/haecker-felix/gradio/archive/master.tar.gz
    prepare: |
      pip3 install meson
    meson-parameters:
      - --buildtype=plain
      - --prefix=/snap/gradio/current/usr
      - -Ddo-post-install=false
    organize:
      snap/gradio/current/usr: usr
    build-packages:
      - intltool
      - valac
      - libglib2.0-dev
      - libgtk-3-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libjson-glib-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
    stage-packages:
      - gstreamer1.0-fluendo-mp3
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
      - libpulse0
    prime:
      - usr/bin/gradio
      - usr/lib/**/*ffmpeg*
      - usr/lib/**/gstreamer-1.0
      - usr/lib/**/gstreamer1.0
      - usr/lib/**/libaa*
      - usr/lib/**/libass*
      - usr/lib/**/libasyncns*
      - usr/lib/**/libav*
      - usr/lib/**/libbluray*
      - usr/lib/**/libbs2b*
      - usr/lib/**/libcaca*
      - usr/lib/**/libcdda*
      - usr/lib/**/libcrystalhd*
      - usr/lib/**/libdv*
      - usr/lib/**/libFLAC*
      - usr/lib/**/libflite*
      - usr/lib/**/libfribidi*
      - usr/lib/**/libgme*
      - usr/lib/**/libgomp*
      - usr/lib/**/libgsm*
      - usr/lib/**/libgst*
      - usr/lib/**/libiec*
      - usr/lib/**/libjack*
      - usr/lib/**/libmodplug*
      - usr/lib/**/libmp3*
      - usr/lib/**/libnuma*
      - usr/lib/**/libogg*
      - usr/lib/**/libopencv*
      - usr/lib/**/libopenjpeg*
      - usr/lib/**/libopus*
      - usr/lib/**/liborc*
      - usr/lib/**/libpulse*
      - usr/lib/**/libraw1394*
      - usr/lib/**/librom1394*
      - usr/lib/**/librtmp*
      - usr/lib/**/libschroedinger*
      - usr/lib/**/libshine*
      - usr/lib/**/libshout*
      - usr/lib/**/libsnappy*
      - usr/lib/**/libsndfile*
      - usr/lib/**/libsodium*
      - usr/lib/**/libsoxr*
      - usr/lib/**/libspeex*
      - usr/lib/**/libssh-gcrypt*
      - usr/lib/**/libtag*
      - usr/lib/**/libtbb*
      - usr/lib/**/libtheora*
      - usr/lib/**/libtwolame*
      - usr/lib/**/libv4l*
      - usr/lib/**/libva*
      - usr/lib/**/libvisual*
      - usr/lib/**/libvorbis*
      - usr/lib/**/libvpx*
      - usr/lib/**/libwavpack*
      - usr/lib/**/libwebp*
      - usr/lib/**/libx264*
      - usr/lib/**/libx265*
      - usr/lib/**/libxvid*
      - usr/lib/**/libzmq*
      - usr/lib/**/libzvbi*
      - usr/lib/**/pulseaudio
      - usr/share/applications/*gradio*
      - usr/share/glib-2.0/schemas/*gradio*
      - usr/share/icons
